/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Btn: typeof import('./src/components/btn.vue')['default']
    CodeBlockNodeView: typeof import('./src/components/Tiptap/CodeBlockNodeView.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElFromItem: typeof import('element-plus/es')['ElFromItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    LoginFrom: typeof import('./src/components/LoginFrom/index.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowEditor: typeof import('./src/components/ShowEditor/index.vue')['default']
    ShowIcon: typeof import('./src/components/showIcon.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    Tiptap: typeof import('./src/components/Tiptap/Tiptap.vue')['default']
    Toolbar: typeof import('./src/components/Tiptap/Toolbar/index.vue')['default']
  }
}
